server:
  port: 3000

spring:
  logging:
    level:
      root: INFO  # Set the default logging level for the entire application
      org.springframework: DEBUG  # Set a specific logging level for Spring packages
      io.chechi.auto: DEBUG  # Set a specific logging level for your project's packages
  config:
    import:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ccdccd
    url: jdbc:mysql://localhost:3306/autoparts?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    scan:
      packages: io.chechi.mymovies.entity
    show-sql: true
    properties:
      hibernate:
        format_sql: true

image:
  upload:
    directory: src/main/resources/images

